#!/bin/bash
# Check if container is launched
CTF_DIR=/home/fdlsifu/Documents/tools/sifuctf/home

# Create a terminal if need
if [ -t 0 ];
then
    EXTERM=""
    BG=""
else
    EXTERM="alacritty -e"
    BG="&"
fi

if [[ $TMUX ]]
then
    EXTERM="alacritty -e"
    BG=""
fi

if [[ -z $(docker container ls -a | grep sifuctf) ]]
then
    # launch container 
    xhost +

    $EXTERM docker run \
        --rm \
        -v /dev/shm:/dev/shm \
        -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=:0 --device /dev/dri \
        --mount type=bind,source=$CTF_DIR,target=/home/sifuctf/ \
        --hostname sifuctf --name sifuctf --user sifuctf \
        -it sifuctf \
        bash -c "cd && /bin/zsh -c tmux" $BG
else
    # attach to existing container 
    $EXTERM docker exec --user sifuctf -it sifuctf tmux att &
fi
